# Generated by Django 3.0.5 on 2020-04-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='some_value', max_length=30)),
                ('name', models.CharField(default='some_value', max_length=30)),
                ('age', models.IntegerField()),
                ('Address', models.CharField(max_length=80)),
                ('postcode', models.IntegerField()),
                ('telephone', models.IntegerField()),
                ('aval_days', models.IntegerField()),
                ('aval_time', models.IntegerField()),
                ('longitude', models.IntegerField(default='1')),
                ('latitude', models.IntegerField(default='1')),
            ],
        ),
        migrations.CreateModel(
            name='Trainer_Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('name', models.CharField(default='some_value', max_length=100)),
                ('email', models.CharField(default='some_value', max_length=30)),
                ('age', models.IntegerField()),
                ('speciality', models.CharField(max_length=100)),
                ('qualification', models.CharField(max_length=30)),
                ('Address_of', models.CharField(max_length=80)),
                ('postcode', models.IntegerField()),
                ('longitude', models.IntegerField(default='1')),
                ('latitude', models.IntegerField(default='1')),
                ('telephone', models.CharField(max_length=30)),
                ('aval_days', models.IntegerField()),
                ('aval_time', models.IntegerField()),
                ('ser_offered', models.CharField(max_length=100)),
                ('profile_picture', models.ImageField(null=True, upload_to='profile', verbose_name='')),
                ('personal_profile', models.CharField(max_length=500)),
                ('additional_pic', models.ImageField(null=True, upload_to='additional', verbose_name='')),
            ],
        ),
    ]
